[package]
name = "treasure"
version = "0.0.1"
authors = ["Christopher J. Stehno <chris@stehno.com>"]
edition = "2018"

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
regex = "1"
rand = "0.6.5"
clap = "2.32.0"
log = "0.4"
fern = "0.5.7"