[package]
name = "treasure"
version = "0.1.0"
authors = ["Christopher J. Stehno <chris.stehno@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
regex = "1"
rand = "0.6.5"