[package]
name = "difficulty"
version = "0.1.0"
authors = ["Christopher J. Stehno <chris.stehno@gmail.com>"]
edition = "2018"
description = "A D&D 5e encounter difficulty calculator."

[dependencies]
clap = {version = "2.32.0", features = ["yaml"]}
log = "0.4"
fern = "0.5.7"